name: Testes com Mocha

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Verificar versões do Node.js e npm
        run: |
          node --version
          npm --version

      - name: Listar arquivos do diretório
        run: ls -la

      - name: Rodar os testes
        run: npm test
